# Generated by Django 3.2.12 on 2023-09-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Approval_List',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('model_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assigned_to', models.CharField(max_length=150)),
                ('approved_date', models.DateField()),
                ('purchase_date', models.DateField()),
                ('inserted_by', models.CharField(max_length=150)),
                ('inserted_date', models.DateField()),
                ('modified_by', models.CharField(max_length=150)),
                ('modified_date', models.DateField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.approvallist')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('mfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Inventory_Items',
            },
        ),
    ]
