# Generated by Django 4.2.5 on 2023-09-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_inventoryitem_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inserted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ItemNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('inserted_by', models.CharField(max_length=250)),
                ('inserted_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventoryitem')),
            ],
            options={
                'verbose_name_plural': 'Item_Notes',
            },
        ),
    ]
