# Generated by Django 4.2.5 on 2023-09-24 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_inserted_date_itemnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inserted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemnotes',
            name='inserted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
