# Generated by Django 4.2.5 on 2023-09-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contact_inserted_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='map_loc',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.maplocation'),
        ),
    ]
