# Generated by Django 4.2.5 on 2023-09-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_area_map_loc_remove_inventoryitem_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='map_loc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.maplocation'),
        ),
    ]
