# Generated by Django 4.2.5 on 2023-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_area_map_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
