# Generated by Django 4.2.5 on 2023-11-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_inventoryitem_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(),
        ),
    ]
