# Generated by Django 4.2.5 on 2024-01-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_inventoryitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
